### ISSUE TITLE
Can't delete product from sidebar cart

### ISSUE THREAD

**Issue by JockChiang** [vuestorefront/vsf-capybara#602] opened 2021-04-22 12:12 UTC
## Current behaviour
Add products to the sidebar cart. 
Click the delete button from the product list.

## Expected behaviour
We should delete the product from the sidebar cart normally.

## Steps to reproduce the issue
See the resource, have no idea.

## Can you handle fixing this bug by yourself?

- [ ] YES
- [x] NO

## Environment details
- Browser: Chrome 90.0.4430.72
- OS: Windows 10, 20H2
- Code Version: master, commit f7eb1b22462d2b38a623eeb5033ab5471758c155

## Additional information
NO

**Comment by dt2patel** [comment] 2021-09-06 16:12
Unable to reproduce this on develop. Closing issue.

**Closed by dt2patel** 2021-09-06 16:12 UTC
Labels: bug
