### ISSUE TITLE
Cannot tab between inputs in user registration modal on demo page

### ISSUE THREAD

**Issue by Agular** [vuestorefront/vsf-capybara#660] opened 2021-07-22 13:49 UTC
## Current behavior

On capybara demo page when arriving to user registration modal after clicking on the user icon and "Register now",
I cannot switch between all the inputs with the tab key. It only seems to switch between the email input and the close button, all other inputs are ignored.
On the other hand, switching between inputs with enter key works.

## Expected behavior

By pressing the Tab key I am able to switch between all the inputs shown in the user registration modal.

## Steps to reproduce the issue

Go to capybara demo page https://capybara.storefrontcloud.io/
Click on user icon
Click on register now
Press Tab to try to navigate between inputs, gets stuck between email and close button

## Can you handle fixing this bug by yourself?

- [ ] YES
- [X] NO

## Environment details

- Browser: Google Chrome 92.0.4515.107
- OS: Windows 10 Enterprise, 1909
- Capybara Demo Page @ 22.07.2021 16:42 GMT+3

## Additional information

Does this happen due to content dynamically changing in the model and thus the tab order is not updated?
Reporting this currently since we have a similar situation where we use SfTabs in a modal and we have 2 inputs in the second tab and the last input is not included in the tab order

**Comment by ymaheshwari1** [comment] 2021-09-27 05:47
Hi @Agular, the issue is fixed in this PR: https://github.com/vuestorefront/vsf-capybara/pull/580. You can update the code directly until the PR does not gets merged.

**Comment by ymaheshwari1** [comment] 2021-12-03 13:56
@dt2patel I think we can close the issue, duplicate of https://github.com/vuestorefront/vsf-capybara/issues/434 and already solved in #580

**Comment by dt2patel** [comment] 2021-12-03 14:07
Closing and merging mentioned PR

**Closed** 2021-12-03 14:07 UTC
Labels: bug
