### ISSUE TITLE
[Bug] Order placing sometimes is not working

### ISSUE THREAD

**Issue by akrajna** [vuestorefront/vsf-capybara#392] opened 2020-06-09 11:33 UTC
## Current behavior
Sometimes it is impossible to place an order, after clinking on 'place the order' button the information 'The order can not be transfered because of server error. Order has been queued ' appears. 
It appears mostly in 'incognito' mode. After user gets all the way back to the 'Details' (by cling on 
Edit payment, Edit shipping, Edit Details) and again through the checkout steps without changing anything (by clicking on continue to shipping, continue to payment, go review the order) placing order is possible. 

## Expected behavior
Placing order is possible in incognito mode whiteout going twice through the checkout.

## Steps to reproduce the issue

1. open the page in incognito mode
2. add any product to the cart
3. go to checkout
4. go thorough all the checkout steps
5. click on 'place the order' button
6. see the error
7. click in turn on: Edit payment, Edit shipping, Edit Details
8. clicking in turn on: 'continue to shipping', 'continue to payment', 'go review the order' buttons
9. click on 'place the order' button
10. see the error

## Can you handle fixing this bug by yourself?

- [ ] YES
- [ ] NO

## Environment details

- Browser: 
- OS: 
- Code Version: 

## Additional information
![orderNotWork](https://user-images.githubusercontent.com/57936972/84142773-b1ca7900-aa55-11ea-9ba6-c49c23880798.gif)

**Comment by dt2patel** [comment] 2021-09-06 15:39
Unable to reproduce right now. Closing issue.

**Closed by dt2patel** 2021-09-06 15:39 UTC
Labels: bug, P0: Critical
